[package]
name = "gtk-rs-mac-demo"
version = "0.1.0"
authors = ["Phil Proctor <philliptproctor@gmail.com>"]
edition = "2018"
description = "GTK Macros"
repository = ""
keywords = []
categories = []
license = "MIT"
#readme = "README.md"

[[bin]]
name = "gtk-rs-mac-demo"
path = "main.rs"
